env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - react
  - '@typescript-eslint'
rules: {
  '@typescript-eslint/no-explicit-any': 0,
  '@typescript-eslint/ban-ts-comment': 0,
}
settings: 
  react: 
    version: detect

